#!/usr/bin/env node
'use strict';
// Deliberately on-demand: replay cadence must remain dedicated to evidence collection.
const crypto=require('node:crypto'),ML=require('../ml-engine.js');
const API=(process.env.MARKET_EDGE_API||'https://market-edge-ai.jakob-market-edge.workers.dev').replace(/\/$/,''),TOKEN=process.env.MARKET_EDGE_RESEARCH_TOKEN||'',DATASET='EARLY-WINDOW-RESEARCH-V1',CODE_VERSION='ml-research-v2-strategy-context',MIN_TRAIN=25;
const finite=value=>{const n=Number(value);return Number.isFinite(n)?n:null;},mean=values=>values.length?values.reduce((a,b)=>a+b,0)/values.length:0,median=values=>{const v=values.slice().sort((a,b)=>a-b),m=Math.floor(v.length/2);return v.length?v.length%2?v[m]:(v[m-1]+v[m])/2:null;};
function hash(value){return crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex').slice(0,16);}
function parse(value){try{return JSON.parse(value||'{}');}catch{return{};}}
function number(value,fallback=0){const n=finite(value);return n==null?fallback:n;}
function sample(row){
  const f=parse(row.features_json),t=parse(row.targets_json),h4=f.h4||{},m15=f.m15||{};
  // All values below are immutable fields captured at the decision timestamp.
  const strategy=String(row.strategy||''),regime=String(row.regime||'');
  const features={quality:number(row.quality_score)/100,rr:number(row.rr),long:row.direction==='long'?1:0,
    trendContinuation:strategy==='TREND CONTINUATION'?1:0,breakout:strategy==='BREAKOUT + RETEST'?1:0,momentum:strategy==='MOMENTUM CONTINUATION'?1:0,meanReversion:strategy==='MEAN REVERSION'?1:0,liquiditySweep:strategy==='LIQUIDITY-SWEEP REVERSAL'?1:0,
    regimeTrend:/UPTREND|DOWNTREND/.test(regime)?1:0,regimeRange:/RANGE/.test(regime)?1:0,regimeBreakout:/BREAKOUT/.test(regime)?1:0,regimeCompression:regime==='COMPRESSION'?1:0,
    h4Rsi:number(h4.rsi)/100,h4Roc5:number(h4.roc5),h4RelativeVolume:number(h4.relativeVolume),m15Rsi:number(m15.rsi)/100,m15RelativeVolume:number(m15.relativeVolume)};
  return ML.makeSample({id:row.signal_id,time:number(row.timestamp),asset:row.asset,strategy:row.strategy,direction:row.direction,regime:row.regime,features,targets:{tp1BeforeSl:t.TP1_BEFORE_SL?1:0,finalR:number(t.FINAL_R)}});
}
function classification(predictions,actual){const n=actual.length,base=mean(actual),labels=predictions.map(value=>value>=.5?1:0),tp=labels.filter((v,i)=>v&&actual[i]).length,fp=labels.filter((v,i)=>v&&!actual[i]).length,fn=labels.filter((v,i)=>!v&&actual[i]).length,tn=labels.filter((v,i)=>!v&&!actual[i]).length;return{n,accuracy:n?labels.filter((v,i)=>v===actual[i]).length/n:null,precision:tp+fp?tp/(tp+fp):null,recall:tp+fn?tp/(tp+fn):null,brier:ML.brier(predictions,actual),ece:ML.expectedCalibrationError(predictions,actual,Math.min(5,n)),baselineBrier:ML.brier(actual.map(()=>base),actual),meanProbability:mean(predictions),eventRate:base,confusion:{tp,fp,fn,tn}};}
function regression(predicted,actual){const baseline=mean(actual),errors=predicted.map((v,i)=>v-actual[i]),baseErrors=actual.map(v=>baseline-v),cov=mean(predicted.map((v,i)=>(v-mean(predicted))*(actual[i]-mean(actual)))),sd=v=>Math.sqrt(mean(v.map(x=>(x-mean(v))**2)));return{n:actual.length,mae:mean(errors.map(Math.abs)),rmse:Math.sqrt(mean(errors.map(x=>x*x))),baselineMae:mean(baseErrors.map(Math.abs)),baselineRmse:Math.sqrt(mean(baseErrors.map(x=>x*x))),correlation:sd(predicted)&&sd(actual)?cov/(sd(predicted)*sd(actual)):null};}
function buckets(predictions,rows){const ordered=predictions.map((score,index)=>({score,row:rows[index]})).sort((a,b)=>a.score-b.score),size=Math.max(1,Math.floor(ordered.length/3));return ['lowest','middle','highest'].map((name,index)=>{const group=index===2?ordered.slice(index*size):ordered.slice(index*size,(index+1)*size),r=group.map(item=>item.row.targets.finalR);return{name,n:group.length,meanFinalR:mean(r),medianFinalR:median(r),meanScore:mean(group.map(item=>item.score))};});}
function evaluate(rows){
  const ordered=[...rows].sort((a,b)=>a.time-b.time),classificationPredictions=[],regressionPredictions=[],actualClass=[],actualR=[],evalRows=[];
  for(let index=MIN_TRAIN;index<ordered.length;index++){const train=ordered.slice(0,index),row=ordered[index],logistic=ML.trainLogistic(train,'tp1BeforeSl'),ridge=ML.trainRidge(train,'finalR');classificationPredictions.push(ML.predictProbability(logistic,row.features));regressionPredictions.push(ML.predictR(ridge,row.features));actualClass.push(row.targets.tp1BeforeSl);actualR.push(row.targets.finalR);evalRows.push(row);}
  const finalTrain=ordered.slice(0,Math.max(MIN_TRAIN,Math.floor(ordered.length*.8))),logistic=ML.trainLogistic(finalTrain,'tp1BeforeSl'),ridge=ML.trainRidge(finalTrain,'finalR');
  return{ordered,finalTrain,logistic,ridge,classification:classification(classificationPredictions,actualClass),regression:regression(regressionPredictions,actualR),buckets:buckets(classificationPredictions,evalRows),classificationPredictions,regressionPredictions,evalRows,oosN:evalRows.length};
}
async function request(path,method='GET',body){const response=await fetch(`${API}${path}`,{method,headers:{authorization:`Bearer ${TOKEN}`,...(body?{'content-type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`${method} ${path}: ${data?.error?.message||response.status}`);return data;}
async function train(){if(!TOKEN)throw new Error('MARKET_EDGE_RESEARCH_TOKEN is required');const source=await request(`/v1/research/ml/dataset?id=${encodeURIComponent(DATASET)}`),rows=source.rows.map(sample),result=evaluate(rows),positive=rows.filter(row=>row.targets.tp1BeforeSl===1).length,negative=rows.length-positive,config={datasetHash:source.dataset.dataset_hash,datasetN:rows.length,featureSchema:'pre-entry-compact-v1',codeVersion:CODE_VERSION,seed:'deterministic-gradient-descent-v1',temporal:{minimumTrain:MIN_TRAIN,walkForward:true}};
  const records=[['TP1-LR-GEN1','regularized-logistic','TP1_BEFORE_SL',result.logistic,result.classification],['FINALR-RIDGE-GEN1','ridge-regression','FINAL_R',result.ridge,result.regression]].map(([name,algorithm,target,model,metrics])=>{const id=`${name}-${hash([config,target,model])}`,baseline=target==='TP1_BEFORE_SL'?metrics.baselineBrier:metrics.baselineMae,metric=target==='TP1_BEFORE_SL'?metrics.brier:metrics.mae,improves=metric<baseline,status=result.oosN>=100&&improves?'SHADOW':'RESEARCH';return{id,status,algorithm,dataset_hash:config.datasetHash,metadata:{...config,modelName:name,target,hyperparameters:{iterations:model.iterations,learningRate:target==='TP1_BEFORE_SL'?.08:.05,l2:model.l2},trainingWindow:{start:result.finalTrain[0].time,end:result.finalTrain.at(-1).time,n:result.finalTrain.length},oosN:result.oosN,metrics,baselineComparison:{metric,baseline,improves},calibration:target==='TP1_BEFORE_SL'?{status:'NOT_APPLIED',reason:`Only ${result.oosN} chronological OOS rows; no calibration fit on the final evaluation segment.`}:null,status,promotionReason:status==='SHADOW'?'All configured gates passed':'Research only: forward shadow requires at least 100 genuine OOS predictions and later genuine forward evidence.',featureImportance:ML.featureImportance(model),model}};});
  const payload={operation:'ml_research_commit',dataset_id:DATASET,dataset_hash:config.datasetHash,dataset_n:rows.length,class_balance:{positive,negative},models:records,run_id:`ml-${hash([config,records.map(r=>r.id)])}`};const saved=await request('/v1/research/ml/ingest','POST',payload);console.log(JSON.stringify({dataset:source.dataset,classBalance:{positive,negative},oosN:result.oosN,classification:result.classification,regression:result.regression,buckets:result.buckets,models:records.map(r=>({id:r.id,status:r.status,target:r.metadata.target})),saved},null,2));}
if(require.main===module)train().catch(error=>{console.error(`ML research failed: ${error.message}`);process.exitCode=1;});
module.exports={sample,classification,regression,buckets,evaluate};
