import {COINBASE_PRODUCTS,INTERVAL_MS,normalizeBinanceKlines} from './monitor-core.mjs';

export const HISTORICAL_VERSION='1.0.0';
export const PRIORITY_ASSETS=['BTC','ETH','SOL','XRP','DOGE','LTC'];
const BASE_INTERVAL='5m',PAGE_CANDLES=300,DAY_MS=86_400_000;

function hash(value){const text=JSON.stringify(value);let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16).padStart(8,'0');}
async function timedFetch(fetchImpl,url,options,timeoutMs=6_000){const controller=new AbortController();let timer;const request=Promise.resolve().then(()=>fetchImpl(url,{...options,signal:controller.signal}));request.catch(()=>{});const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>{controller.abort();reject(new Error(`historical request exceeded ${timeoutMs}ms`));},timeoutMs);});try{return await Promise.race([request,timeout]);}finally{clearTimeout(timer);}}
function utcFloor(time,interval){return Math.floor(time/interval)*interval;}
function statementRows(db,sql,args=[]){return db.prepare(sql).bind(...args).all().then(result=>result.results||[]);}
function stateFor(asset,now,days){const interval=INTERVAL_MS[BASE_INTERVAL],end=utcFloor(now,interval),start=utcFloor(end-days*DAY_MS,interval),product=COINBASE_PRODUCTS[asset];if(!product)throw new Error(`${asset} has no approved historical source`);return{asset,exchange:'COINBASE',symbol:product,quoteCurrency:'USD',baseInterval:BASE_INTERVAL,targetStart:start,targetEnd:end,cursorStart:start,status:'BUILDING'};}
async function coinbasePage(state,fetchImpl,now){
  const interval=INTERVAL_MS[BASE_INTERVAL],from=Math.max(state.targetStart,Number(state.cursorStart)||state.targetStart),to=Math.min(state.targetEnd-interval,from+(PAGE_CANDLES-1)*interval),url=`https://api.exchange.coinbase.com/products/${encodeURIComponent(state.symbol)}/candles?granularity=300&start=${encodeURIComponent(new Date(from).toISOString())}&end=${encodeURIComponent(new Date(to).toISOString())}`;
  let failure='';
  for(let attempt=0;attempt<2;attempt++){
    let response;try{response=await timedFetch(fetchImpl,url,{headers:{accept:'application/json','user-agent':'MarketEdgeResearch/1.2 (historical cache)'}});}catch(error){failure=`${state.asset} Coinbase ${String(error.message||error)}`;if(attempt)break;await new Promise(resolve=>setTimeout(resolve,800));continue;}
    if(response.ok){const rows=await response.json(),adapted=(Array.isArray(rows)?rows:[]).map(row=>[Number(row?.[0])*1000,row?.[3],row?.[2],row?.[1],row?.[4],row?.[5],Number(row?.[0])*1000+interval-1]);const report=normalizeBinanceKlines(adapted,{asset:state.asset,symbol:state.symbol,interval:BASE_INTERVAL,now});if(report.status==='INVALID')throw new Error(`${state.asset} historical page rejected: ${report.errors.slice(0,2).join('; ')}`);return{report,from,to,url};}
    failure=`${state.asset} Coinbase HTTP ${response.status}: ${(await response.text().catch(()=>'' )).replace(/\s+/g,' ').slice(0,100)}`;
    if(![400,408,425,429,500,502,503,504].includes(response.status)||attempt)break;
    await new Promise(resolve=>setTimeout(resolve,400));
  }
  throw new Error(failure||`${state.asset} Coinbase historical request failed`);
}
async function persistPage(db,state,page,now){
  const statements=page.report.candles.map(candle=>db.prepare(`INSERT OR IGNORE INTO canonical_candles (asset,exchange,symbol,interval,open_time,close_time,open,high,low,close,volume,source_latency_ms,received_at,dataset_hash) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(state.asset,state.exchange,state.symbol,BASE_INTERVAL,candle.time,candle.closeTime,candle.open,candle.high,candle.low,candle.close,candle.volume,null,now,page.report.datasetHash));
  for(let index=0;index<statements.length;index+=100)await db.batch(statements.slice(index,index+100));
  const nextCursor=page.to+INTERVAL_MS[BASE_INTERVAL],complete=nextCursor>=state.targetEnd,expected=Math.max(0,Math.floor((state.targetEnd-state.targetStart)/INTERVAL_MS[BASE_INTERVAL])),cumulative=(Number(state.candleCount)||0)+page.report.candles.length,manifest={datasetId:`dataset-${hash([state.asset,state.exchange,state.symbol,state.targetStart,state.targetEnd,BASE_INTERVAL])}`,asset:state.asset,exchange:state.exchange,symbol:state.symbol,quoteCurrency:state.quoteCurrency,provider:'COINBASE',baseTimeframe:BASE_INTERVAL,startTimestamp:state.targetStart,endTimestamp:state.targetEnd,downloadTimestamp:now,candleCount:cumulative,expectedCandles:expected,missingCandles:page.report.missing,duplicates:0,gaps:page.report.gaps,partialCandlesExcluded:page.report.partial,coverage:expected?cumulative/expected:0,datasetHash:page.report.datasetHash,datasetVersion:`${HISTORICAL_VERSION}:${state.exchange}:${state.symbol}:${BASE_INTERVAL}`,status:complete?'COMPLETE':'BUILDING'};
  await db.prepare(`INSERT INTO historical_dataset_manifests (dataset_id,asset,exchange,symbol,quote_currency,base_timeframe,target_start,target_end,cursor_start,status,downloaded_at,candle_count,expected_candles,missing_candles,duplicate_count,gap_count,partial_excluded,coverage,dataset_hash,dataset_version,manifest_json,last_error,completed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(asset,exchange,base_timeframe) DO UPDATE SET cursor_start=excluded.cursor_start,status=excluded.status,downloaded_at=excluded.downloaded_at,candle_count=excluded.candle_count,expected_candles=excluded.expected_candles,missing_candles=excluded.missing_candles,duplicate_count=excluded.duplicate_count,gap_count=excluded.gap_count,partial_excluded=excluded.partial_excluded,coverage=excluded.coverage,dataset_hash=excluded.dataset_hash,dataset_version=excluded.dataset_version,manifest_json=excluded.manifest_json,last_error=NULL,completed_at=excluded.completed_at`).bind(manifest.datasetId,state.asset,state.exchange,state.symbol,state.quoteCurrency,BASE_INTERVAL,state.targetStart,state.targetEnd,nextCursor,manifest.status,now,manifest.candleCount,manifest.expectedCandles,manifest.missingCandles,manifest.duplicates,manifest.gaps,manifest.partialCandlesExcluded,manifest.coverage,manifest.datasetHash,manifest.datasetVersion,JSON.stringify(manifest),null,complete?now:null).run();
  return manifest;
}
async function persistFailure(db,state,error,now){await db.prepare(`INSERT INTO historical_dataset_manifests (dataset_id,asset,exchange,symbol,quote_currency,base_timeframe,target_start,target_end,cursor_start,status,downloaded_at,candle_count,expected_candles,missing_candles,duplicate_count,gap_count,partial_excluded,coverage,dataset_hash,dataset_version,manifest_json,last_error,completed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(asset,exchange,base_timeframe) DO UPDATE SET status='DEGRADED',downloaded_at=excluded.downloaded_at,last_error=excluded.last_error`).bind(`dataset-${hash([state.asset,state.exchange,state.symbol,state.targetStart,state.targetEnd,BASE_INTERVAL])}`,state.asset,state.exchange,state.symbol,state.quoteCurrency,BASE_INTERVAL,state.targetStart,state.targetEnd,state.cursorStart,'DEGRADED',now,state.candleCount||0,0,0,0,0,0,0,'',HISTORICAL_VERSION,JSON.stringify(state),String(error?.message||error).slice(0,360),null).run();}

export async function runHistoricalBackfill({db,fetchImpl=fetch,now=Date.now(),assets=PRIORITY_ASSETS,days=730,delay=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds))}={}){
  if(!db)return{status:'STORAGE_UNAVAILABLE',assetsRequested:assets.length,assetsCompleted:0,pages:0,errors:['D1 binding is unavailable']};
  const manifests=await statementRows(db,`SELECT * FROM historical_dataset_manifests WHERE base_timeframe=?`,[BASE_INTERVAL]),byAsset=new Map(manifests.map(row=>[row.asset,row]));let completed=0,pages=0;const errors=[],details=[];
  for(let index=0;index<assets.length;index++){
    if(index)await delay(600);const asset=assets[index],cached=byAsset.get(asset),state={...stateFor(asset,now,days),...(cached?{cursorStart:cached.cursor_start,candleCount:cached.candle_count,status:cached.status}:{})};
    if(state.status==='COMPLETE'){completed++;details.push({asset,status:'COMPLETE',cached:true});continue;}
    try{const page=await coinbasePage(state,fetchImpl,now),manifest=await persistPage(db,state,page,now);pages++;if(manifest.status==='COMPLETE')completed++;details.push({asset,status:manifest.status,candles:page.report.candles.length,cursorStart:manifest.endTimestamp===state.cursorStart?state.cursorStart:page.to,coverage:manifest.coverage,datasetHash:manifest.datasetHash});}
    catch(error){errors.push(`${asset}: ${String(error.message||error).slice(0,220)}`);try{await persistFailure(db,state,error,now);}catch(storageError){errors.push(`${asset}: manifest write failed: ${String(storageError.message||storageError).slice(0,100)}`);}details.push({asset,status:'DEGRADED'});}
  }
  return{status:errors.length?(pages||completed?'DEGRADED':'FAILED'):'BUILDING',assetsRequested:assets.length,assetsCompleted:completed,pages,errors,details,executionDisabled:true};
}
export async function latestHistorical(db){if(!db)return{storage:'unavailable',manifests:[]};const manifests=await statementRows(db,`SELECT dataset_id,asset,exchange,symbol,quote_currency,base_timeframe,target_start,target_end,cursor_start,status,downloaded_at,candle_count,expected_candles,missing_candles,duplicate_count,gap_count,partial_excluded,coverage,dataset_hash,dataset_version,last_error,completed_at FROM historical_dataset_manifests ORDER BY asset LIMIT 100`);return{storage:'connected',manifests,executionDisabled:true};}
