// Read-only Market Edge scan adapter. Strategy, sizing, and ML inference remain
// in the existing shared engines; this file only moves live data orchestration
// behind the Worker boundary for the separate customer UI.
import QuantModule from '../quant-engine.js';
import MlModule from '../ml-engine.js';
import '../invo-market-universe.js';

const Quant=globalThis.MarketEdgeQuant||QuantModule;
const ML=globalThis.MarketEdgeML||MlModule;
const HYPERLIQUID_API='https://api.hyperliquid.xyz/info';
const INTERVAL_MS={'5m':300000,'15m':900000,'1h':3600000,'4h':14400000,'1d':86400000};
const MIN_ORDER_NOTIONAL=10;
const DEFAULT_SETTINGS=Object.freeze({balance:7,riskPct:.01,maxLeverage:10,minQuality:72,minRR:1.8,maxExposurePct:1,minNotional:MIN_ORDER_NOTIONAL,requireMTF:true});

function finite(value){const n=Number(value);return Number.isFinite(n)?n:null;}
function clamp(value,min,max){return Math.max(min,Math.min(max,value));}
function mean(values){return values.length?values.reduce((sum,value)=>sum+value,0)/values.length:0;}
function ema(values,period){if(!values.length)return[];const k=2/(period+1),out=[values[0]];for(let i=1;i<values.length;i++)out.push(values[i]*k+out[i-1]*(1-k));return out;}
function sma(values,period){return values.map((_,i)=>i<period-1?null:values.slice(i-period+1,i+1).reduce((a,b)=>a+b,0)/period);}
function rsi(values,period=14){const recent=values.slice(1).map((v,i)=>v-values[i]).slice(-period),gains=mean(recent.map(v=>Math.max(v,0))),losses=mean(recent.map(v=>Math.max(-v,0)));if(!losses)return 100;return 100-100/(1+gains/losses);}
function atr(candles,period=14){const ranges=candles.slice(1).map((c,i)=>Math.max(c.high-c.low,Math.abs(c.high-candles[i].close),Math.abs(c.low-candles[i].close)));return mean(ranges.slice(-period));}
function compactError(error){return String(error?.message||error||'Data unavailable').replace(/\s+/g,' ').slice(0,180);}
function hash(value){const text=JSON.stringify(value);let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16).padStart(8,'0');}

function validatedSettings(input={}){
  const source=input&&typeof input==='object'?input:{};
  const number=(key,minimum,maximum,fallback)=>{const value=finite(source[key]);return value!=null&&value>=minimum&&value<=maximum?value:fallback;};
  return {...DEFAULT_SETTINGS,balance:number('balance',0.01,1_000_000,DEFAULT_SETTINGS.balance),riskPct:number('riskPct',.001,.05,DEFAULT_SETTINGS.riskPct),maxLeverage:number('maxLeverage',1,10,DEFAULT_SETTINGS.maxLeverage),maxExposurePct:number('maxExposurePct',.01,1,DEFAULT_SETTINGS.maxExposurePct)};
}

const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function fetchJson(fetchImpl,url,options,timeoutMs=6000){
  for(let attempt=0;attempt<3;attempt++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try { const response=await fetchImpl(url,{...options,signal:controller.signal});if(response.ok)return await response.json();if((response.status===429||response.status>=500)&&attempt<2){await delay(1200*(attempt+1));continue;}throw new Error(`HTTP ${response.status}`); } finally { clearTimeout(timer); }}
}
function completedCandles(rows,interval,now){
  const duration=INTERVAL_MS[interval];
  const candles=(Array.isArray(rows)?rows:[]).map(row=>({time:finite(row?.t),open:finite(row?.o),high:finite(row?.h),low:finite(row?.l),close:finite(row?.c),volume:finite(row?.v)})).filter(candle=>Object.values(candle).every(Number.isFinite)&&candle.time+duration<=now&&candle.open>0&&candle.high>=Math.max(candle.open,candle.close)&&candle.low<=Math.min(candle.open,candle.close)&&candle.low>0).sort((a,b)=>a.time-b.time);
  if(candles.length<60)throw new Error(`Insufficient completed ${interval} candles`);
  if(now-candles.at(-1).time>duration*3)throw new Error(`Stale ${interval} candles`);
  return candles;
}
async function hyperCandles(coin,interval,bars,fetchImpl,now){
  const duration=INTERVAL_MS[interval],rows=await fetchJson(fetchImpl,HYPERLIQUID_API,{method:'POST',headers:{accept:'application/json','content-type':'application/json'},body:JSON.stringify({type:'candleSnapshot',req:{coin,interval,startTime:now-bars*duration,endTime:now}})});
  return completedCandles(rows,interval,now);
}
async function binanceCandles(coin,fetchImpl,now){
  const rows=await fetchJson(fetchImpl,`https://api.binance.com/api/v3/klines?symbol=${encodeURIComponent(coin)}USDT&interval=4h&limit=500`,{headers:{accept:'application/json'}});
  const duration=INTERVAL_MS['4h'],candles=(Array.isArray(rows)?rows:[]).map(row=>({time:finite(row?.[0]),open:finite(row?.[1]),high:finite(row?.[2]),low:finite(row?.[3]),close:finite(row?.[4]),volume:finite(row?.[5]),closeTime:finite(row?.[6])})).filter(c=>Object.values(c).every(Number.isFinite)&&c.closeTime<=now&&c.open>0&&c.high>=Math.max(c.open,c.close)&&c.low<=Math.min(c.open,c.close)).map(({closeTime,...candle})=>candle).sort((a,b)=>a.time-b.time);
  if(candles.length<60||now-candles.at(-1).time>duration*3)throw new Error('Missing or stale Binance 4h candles');
  return candles;
}
function resampleFourHours(hourly,now){
  const span=INTERVAL_MS['4h'],buckets=new Map();
  hourly.filter(c=>c.time+INTERVAL_MS['1h']<=now).sort((a,b)=>a.time-b.time).forEach(candle=>{const time=Math.floor(candle.time/span)*span,existing=buckets.get(time);if(!existing)buckets.set(time,{time,open:candle.open,high:candle.high,low:candle.low,close:candle.close,volume:candle.volume});else{existing.high=Math.max(existing.high,candle.high);existing.low=Math.min(existing.low,candle.low);existing.close=candle.close;existing.volume+=candle.volume;}});
  return [...buckets.values()].filter(c=>c.time+span<=now);
}
async function coinbaseCandles(coin,fetchImpl,now){
  const rows=await fetchJson(fetchImpl,`https://api.exchange.coinbase.com/products/${encodeURIComponent(coin)}-USDT/candles?granularity=3600`,{headers:{accept:'application/json'}});
  const hourly=(Array.isArray(rows)?rows:[]).map(row=>({time:finite(row?.[0])*1000,low:finite(row?.[1]),high:finite(row?.[2]),open:finite(row?.[3]),close:finite(row?.[4]),volume:finite(row?.[5])})).filter(c=>Object.values(c).every(Number.isFinite)&&c.open>0&&c.high>=Math.max(c.open,c.close)&&c.low<=Math.min(c.open,c.close));
  const candles=resampleFourHours(hourly,now);
  if(candles.length<60||now-candles.at(-1).time>INTERVAL_MS['4h']*3)throw new Error('Missing or stale Coinbase 4h candles');
  return candles;
}
function scoreMarket(symbol,candles,source){
  const validation=Quant.validateCandles(candles);if(!validation.valid)throw new Error(`${source} data rejected: ${validation.reason}`);
  const closes=candles.map(c=>c.close),volumes=candles.map(c=>c.volume),e20=ema(closes,20),e50=ema(closes,50),e12=ema(closes,12),e26=ema(closes,26),macd=e12.map((v,i)=>v-e26[i]),signal=ema(macd,9),price=closes.at(-1),currentRsi=rsi(closes),currentAtr=atr(candles),avgVol=sma(volumes,20).at(-1)||volumes.at(-1),volumeRatio=volumes.at(-1)/avgVol,change24=(price/(closes.at(-7)||closes[0])-1)*100,trendUp=price>e20.at(-1)&&e20.at(-1)>e50.at(-1),trendDown=price<e20.at(-1)&&e20.at(-1)<e50.at(-1),momentumUp=macd.at(-1)>signal.at(-1);
  let longScore=0,shortScore=0,longReasons=[],shortReasons=[];
  if(trendUp){longScore+=3;longReasons.push('Price and moving averages are aligned upward');}else if(trendDown){longScore-=2;longReasons.push('Primary trend is pointing down');}else longReasons.push('Trend is mixed and needs confirmation');
  if(currentRsi>=48&&currentRsi<=67){longScore+=2;longReasons.push(`RSI ${currentRsi.toFixed(0)} supports upward momentum`);}else if(currentRsi>74){longScore-=2;longReasons.push(`RSI ${currentRsi.toFixed(0)} warns against chasing higher`);}else if(currentRsi<40)longReasons.push(`RSI ${currentRsi.toFixed(0)} shows weak upward momentum`);
  if(momentumUp){longScore++;longReasons.push('MACD momentum is improving');}else{longScore--;longReasons.push('MACD momentum is fading');}if(volumeRatio>=1.15){longScore++;longReasons.push(`Volume is ${volumeRatio.toFixed(1)}× its 20-bar average`);}if(change24>12){longScore-=2;longReasons.push(`Already up ${change24.toFixed(1)}%—pullback risk is high`);}else if(change24>0&&change24<=8)longScore++;
  if(trendDown){shortScore+=3;shortReasons.push('Price and moving averages are aligned downward');}else if(trendUp){shortScore-=2;shortReasons.push('Primary trend is still pointing up');}else shortReasons.push('Trend is mixed and needs confirmation');
  if(currentRsi>=33&&currentRsi<=52){shortScore+=2;shortReasons.push(`RSI ${currentRsi.toFixed(0)} supports downward momentum`);}else if(currentRsi<26){shortScore-=2;shortReasons.push(`RSI ${currentRsi.toFixed(0)} warns against chasing lower`);}else if(currentRsi>60)shortReasons.push(`RSI ${currentRsi.toFixed(0)} is too strong for a clean short`);
  if(!momentumUp){shortScore++;shortReasons.push('MACD momentum is weakening');}else{shortScore--;shortReasons.push('MACD momentum is improving');}if(volumeRatio>=1.15){shortScore++;shortReasons.push(`Volume is ${volumeRatio.toFixed(1)}× its 20-bar average`);}if(change24<-12){shortScore-=2;shortReasons.push(`Already down ${Math.abs(change24).toFixed(1)}%—bounce risk is high`);}else if(change24<0&&change24>=-8)shortScore++;
  longScore=clamp(longScore,0,8);shortScore=clamp(shortScore,0,8);const direction=longScore>=6&&longScore>shortScore?'long':shortScore>=6&&shortScore>longScore?'short':null,score=direction==='short'?shortScore:direction==='long'?longScore:Math.max(longScore,shortScore),action=direction==='long'?'buy':direction==='short'?'short':score>=4?'watch':'avoid';
  return {symbol,price,change24,rsi:currentRsi,atr:currentAtr,volumeRatio,score,action,direction,reasons:direction==='short'?shortReasons:longReasons,source,longScore,shortScore,candles};
}
async function pool(items,worker,concurrency=4){const output=new Array(items.length),queue=[...items.keys()];await Promise.all(Array.from({length:Math.min(concurrency,items.length)},async()=>{while(queue.length){const index=queue.shift();try{output[index]=await worker(items[index]);}catch(error){output[index]={error:compactError(error)};}}}));return output;}
function features(candidate){const frame=candidate.frame||{},m15=candidate.timeframes?.m15||{},strategy=String(candidate.strategy||''),regime=String(candidate.regime||'');return{quality:Number(candidate.setupQuality??candidate.quality??0)/100,rr:Number(candidate.rr1??candidate.rr??0),long:candidate.direction==='long'?1:0,trendContinuation:strategy==='TREND CONTINUATION'?1:0,breakout:strategy==='BREAKOUT + RETEST'?1:0,momentum:strategy==='MOMENTUM CONTINUATION'?1:0,meanReversion:strategy==='MEAN REVERSION'?1:0,liquiditySweep:strategy==='LIQUIDITY-SWEEP REVERSAL'?1:0,regimeTrend:/UPTREND|DOWNTREND/.test(regime)?1:0,regimeRange:/RANGE/.test(regime)?1:0,regimeBreakout:/BREAKOUT/.test(regime)?1:0,regimeCompression:regime==='COMPRESSION'?1:0,h4Rsi:Number(frame.rsi??0)/100,h4Roc5:Number(frame.roc5??0),h4RelativeVolume:Number(frame.relativeVolume??0),m15Rsi:Number(m15.rsi??0)/100,m15RelativeVolume:Number(m15.relativeVolume??0)};}
function withMl(quant,candidates,activeModel){const eligible=(candidates||[]).filter(c=>c.decision==='TAKE TRADE'&&c.risk?.valid),base={...quant,mlWeight:0,mlInferenceAttempts:0,mlInferenceSuccesses:0,mlInferenceFailures:0,candidateCount:candidates?.length||0,actionableCandidateCount:eligible.length,quantStrategyPick:{strategy:quant.strategy||null,direction:quant.direction||null}};if(!activeModel?.available||activeModel.target!=='TP1_BEFORE_SL'||!eligible.length)return base;const weight=activeModel.status==='CHAMPION'&&activeModel.calibration?.status==='APPLIED' ? .25 : activeModel.status==='SHADOW' ? .1 : .05,ranked=eligible.map(candidate=>{let raw=null;try{raw=ML.predictProbability(activeModel.model,features(candidate))*100;}catch{}return {...candidate,mlRawScore:raw,combinedScore:Number.isFinite(raw)?candidate.setupQuality*(1-weight)+raw*weight:candidate.setupQuality,modelId:activeModel.id,modelStatus:activeModel.status};}).sort((a,b)=>b.combinedScore-a.combinedScore||b.setupQuality-a.setupQuality||String(a.candidateKey).localeCompare(String(b.candidateKey))),selected=ranked[0]||quant,successes=ranked.filter(c=>Number.isFinite(c.mlRawScore)).length;return {...selected,mlWeight:weight,mlStrategyInfluence:`${Math.round(weight*100)}% · ${activeModel.status} EXPERIMENTAL`,mlAssistedStrategyPick:{strategy:selected.strategy,direction:selected.direction},mlInferenceAttempts:eligible.length,mlInferenceSuccesses:successes,mlInferenceFailures:eligible.length-successes,candidateCount:candidates.length,actionableCandidateCount:eligible.length,quantStrategyPick:{strategy:quant.strategy||null,direction:quant.direction||null},candidateScores:ranked.map(c=>({strategy:c.strategy,direction:c.direction,quantScore:c.setupQuality,mlRawScore:c.mlRawScore,combinedScore:c.combinedScore,modelId:c.modelId,modelStatus:c.modelStatus}))};}
function responseResult(result,rank=null){const q=result.quant||{},risk=q.risk?.valid?q.risk:null,entryStatus=q.decision==='TAKE TRADE'?'TRADE_READY':q.decision==='WAIT'?'WAIT_FOR_ENTRY':q.decision==='ANALYSIS UNAVAILABLE'?'DATA_UNAVAILABLE':'NO_VALID_SETUP',mlApplicable=Number(q.mlInferenceAttempts||0)>0,mlStatus=q.modelStatus||(mlApplicable?'SCORE_UNAVAILABLE':'NOT_APPLICABLE'),mlReason=mlApplicable?(Number(q.mlInferenceSuccesses||0)>0?'ML score unavailable for this ranked candidate':'ML inference did not produce a score for this candidate'):'No eligible TAKE TRADE candidate reached ML ranking';return {rank,asset:result.symbol,instrument:result.invoInstrument,direction:q.direction||null,strategy:q.strategy||null,current_price:result.price,entry:q.entry??null,entry_zone:q.entryZone||null,stop:q.stop??null,tp1:q.target1??null,tp2:q.target2??null,rr1:q.rr1??q.rr??null,rr2:q.rr2??null,setup_quality:q.setupQuality??null,entry_status:entryStatus,strict_verdict:q.decision||'ANALYSIS UNAVAILABLE',quant_score:q.setupQuality??null,ml_score:Number.isFinite(q.mlRawScore)?q.mlRawScore:null,combined_score:Number.isFinite(q.combinedScore)?q.combinedScore:q.setupQuality??null,ml:{model_id:q.modelId||null,status:mlStatus,weight:q.mlWeight||0,reason:mlReason},position:risk?{notional:risk.notional,margin:risk.margin,leverage:risk.leverage,risk_amount:risk.maxLoss,estimated_costs:risk.notional*risk.roundTripCostPct,allocation:result.settings?.balance?risk.margin/result.settings.balance:null}:null,regime:q.regime||null,reasoning:q.reason||null,caution:q.decision==='TAKE TRADE'?null:(q.reason||'No valid current entry'),source_count:result.sourceCount||0,data_quality:result.sourceCount>=2?'MULTI_SOURCE':'SINGLE_SOURCE',scan_snapshot_id:hash([result.symbol,q.direction,q.strategy,q.entry,q.stop,q.target1,q.target2,q.modelId])};}

const CHART_TIMEFRAMES=Object.freeze({'5m':220,'15m':200,'1h':180,'4h':160,'1d':140});
export async function fetchLiveMarketChart({asset,timeframe='15m',fetchImpl=fetch,now=Date.now()}={}){
  const instrument=String(asset||'').trim().toUpperCase();
  if(!/^[A-Z0-9]{2,20}$/.test(instrument))throw Object.assign(new Error('A valid Invo instrument is required'),{status:400,code:'INVALID_ASSET'});
  if(!Object.hasOwn(CHART_TIMEFRAMES,timeframe))throw Object.assign(new Error('Unsupported chart timeframe'),{status:400,code:'INVALID_TIMEFRAME'});
  const candles=await hyperCandles(instrument,timeframe,CHART_TIMEFRAMES[timeframe],fetchImpl,now);
  return {asset:instrument,timeframe,source:'HYPERLIQUID',capturedAt:now,candles};
}

export async function runLiveScan({fetchImpl=fetch,now=Date.now(),settings:settingsInput,activeModel=null,market:requestedMarket=null,marketMetadata=null,marketRunner=null}={}){
  if(!Quant?.evaluateSetup||!Quant?.evaluateSetupCandidates||!globalThis.MarketEdgeInvoUniverse?.build)throw new Error('Shared Market Edge engine is unavailable');
  const settings=validatedSettings(settingsInput),meta=marketMetadata?null:await fetchJson(fetchImpl,HYPERLIQUID_API,{method:'POST',headers:{accept:'application/json','content-type':'application/json'},body:JSON.stringify({type:'metaAndAssetCtxs'})}),universe=marketMetadata?{totalEligible:1,excluded:0,selected:[marketMetadata]}:globalThis.MarketEdgeInvoUniverse.build(meta,{limit:40}),selected=marketMetadata?[marketMetadata]:requestedMarket?universe.selected.filter(market=>market.invoInstrument===String(requestedMarket).toUpperCase()):universe.selected;if(!selected.length)throw new Error(requestedMarket?'Requested market is not in the current Invo universe':'Invo returned no eligible perpetual instruments');
  const attempted=marketRunner?await pool(selected,market=>marketRunner(market,{settings,now}),2):await pool(selected,async market=>{const settled=await Promise.allSettled([hyperCandles(market.invoInstrument,'4h',500,fetchImpl,now),binanceCandles(market.dataSymbol,fetchImpl,now),coinbaseCandles(market.dataSymbol,fetchImpl,now)]),opinions=settled.map((item,index)=>item.status==='fulfilled'?scoreMarket(market.invoInstrument,item.value,['Hyperliquid','Binance','Coinbase'][index]):null).filter(Boolean);if(!opinions.length)throw new Error(`All feeds unavailable for ${market.invoInstrument}`);const reference=opinions.find(item=>item.source==='Hyperliquid')||opinions[0],avgLongScore=mean(opinions.map(item=>item.longScore)),avgShortScore=mean(opinions.map(item=>item.shortScore)),buyVotes=opinions.filter(item=>item.action==='buy').length,shortVotes=opinions.filter(item=>item.action==='short').length,direction=opinions.length>=2&&buyVotes>=2&&shortVotes===0&&avgLongScore>=6?'long':opinions.length>=2&&shortVotes>=2&&buyVotes===0&&avgShortScore>=6?'short':null,prices=opinions.map(item=>item.price).sort((a,b)=>a-b),medianPrice=prices[Math.floor(prices.length/2)],maxPriceDisagreement=Math.max(...prices.map(price=>Math.abs(price/medianPrice-1))),[m5,m15,h1,d1]=await Promise.all([hyperCandles(market.invoInstrument,'5m',500,fetchImpl,now),hyperCandles(market.invoInstrument,'15m',320,fetchImpl,now),hyperCandles(market.invoInstrument,'1h',420,fetchImpl,now),hyperCandles(market.invoInstrument,'1d',260,fetchImpl,now)]);let quant=Quant.evaluateSetup({timeframes:{m5,m15,h1,h4:reference.candles,d1},social:Quant.aggregateSocial([],market.invoInstrument),settings}),candidates=Quant.evaluateSetupCandidates({timeframes:{m5,m15,h1,h4:reference.candles,d1},social:Quant.aggregateSocial([],market.invoInstrument),settings});quant=withMl(quant,candidates,activeModel);const opinionDirections=opinions.map(item=>item.longScore>item.shortScore?'long':item.shortScore>item.longScore?'short':'neutral'),matchingFeeds=quant.direction?opinionDirections.filter(side=>side===quant.direction).length:0;if(maxPriceDisagreement>.02)quant={...quant,decision:'WAIT',reason:`Exchange prices disagree by up to ${(maxPriceDisagreement*100).toFixed(1)}%`};if(quant.decision==='TAKE TRADE'&&(opinions.length<2||matchingFeeds<2))quant={...quant,decision:'WAIT',reason:'Quantitative setup exists, but fewer than two independent feeds confirm its direction'};return {symbol:market.invoInstrument,invoInstrument:market.invoInstrument,dataSymbol:market.dataSymbol,price:reference.price,sourceCount:opinions.length,sources:opinions.map(item=>item.source),maxPriceDisagreement,matchingFeeds,quant,settings};},2);
  if(marketRunner){const results=attempted.filter(item=>item&&!item.error),failures=attempted.filter(item=>item?.error).map(item=>item.error),geometry=item=>Boolean(item?.position&&[item.entry,item.stop,item.tp1,item.tp2,item.rr1,item.position.notional,item.position.margin,item.position.risk_amount].every(value=>Number.isFinite(Number(value)))),rank=item=>(geometry(item)?10000:0)+Number(item.combined_score??item.setup_quality??-1),rankedOpportunities=results.sort((a,b)=>rank(b)-rank(a)||String(a.asset).localeCompare(String(b.asset))).map((item,index)=>({...item,rank:index+1}),),bestTradeNow=rankedOpportunities.find(item=>item.entry_status==='TRADE_READY'&&geometry(item))||null,bestOpportunity=rankedOpportunities.find(geometry)||rankedOpportunities[0]||null,coverage={requested:selected.length,evaluated:results.length,skipped:failures.length,multiSourceEvaluated:results.filter(item=>item.source_count>=2).length,singleSourceEvaluated:results.filter(item=>item.source_count===1).length};return {scanId:`scan-${hash([now,rankedOpportunities.map(item=>[item.asset,item.entry,item.strict_verdict])])}`,scannedAt:now,status:bestTradeNow?'TRADE_READY':bestOpportunity?.entry_status==='WAIT_FOR_ENTRY'?'WAIT_FOR_ENTRY':bestOpportunity?'NO_VALID_SETUP':'DATA_UNAVAILABLE',universe:{found:universe.totalEligible,scanned:selected.length,evaluated:results.length,excluded:universe.excluded,dataFailures:failures.length},dataQuality:{status:failures.length?'PARTIAL':'MULTI_SOURCE',failures,coverage},scanSummary:{rankedOpportunities:rankedOpportunities.length,actionableNow:bestTradeNow?1:0},rankedOpportunities,bestOpportunity,bestTradeNow};}
  const results=attempted.filter(item=>item&&!item.error),failures=attempted.filter(item=>item?.error).map(item=>item.error),coverage={requested:selected.length,evaluated:results.length,skipped:failures.length,multiSourceEvaluated:results.filter(result=>result.sourceCount>=2).length,singleSourceEvaluated:results.filter(result=>result.sourceCount===1).length};if(!results.length)return {status:'DATA_UNAVAILABLE',scannedAt:now,universe:{found:universe.totalEligible,scanned:selected.length,evaluated:0,excluded:universe.excluded,dataFailures:failures.length},dataQuality:{status:'DATA_UNAVAILABLE',failures,coverage},scanSummary:{rankedOpportunities:0,actionableNow:0},rankedOpportunities:[],bestOpportunity:null,bestTradeNow:null};
  const geometry=q=>Boolean(q?.risk?.valid&&[q.entry,q.stop,q.target1,q.target2,q.rr1??q.rr,q.rr2,q.risk.notional,q.risk.margin,q.risk.maxLoss].every(value=>Number.isFinite(Number(value)))),rank=result=>(geometry(result.quant)?10000:0)+Number(result.quant?.combinedScore??result.quant?.setupQuality??-1);results.sort((a,b)=>rank(b)-rank(a)||String(a.symbol).localeCompare(String(b.symbol)));const best=results.find(result=>geometry(result.quant))||results[0],bestTrade=results.find(result=>result.quant?.decision==='TAKE TRADE'&&geometry(result.quant))||null;
  const rankedOpportunities=results.map((result,index)=>responseResult(result,index+1)),bestTradeResponse=bestTrade?responseResult(bestTrade,rankedOpportunities.find(item=>item.asset===bestTrade.symbol&&item.scan_snapshot_id===responseResult(bestTrade).scan_snapshot_id)?.rank||null):null;
  return {scanId:`scan-${hash([now,results.map(result=>[result.symbol,result.quant?.entry,result.quant?.decision])])}`,scannedAt:now,status:bestTrade?'TRADE_READY':best?.quant?.decision==='WAIT'?'WAIT_FOR_ENTRY':'NO_VALID_SETUP',universe:{found:universe.totalEligible,scanned:selected.length,evaluated:results.length,excluded:universe.excluded,dataFailures:failures.length},dataQuality:{status:failures.length?'PARTIAL':'MULTI_SOURCE',failures,coverage},scanSummary:{rankedOpportunities:rankedOpportunities.length,actionableNow:bestTradeResponse?1:0},rankedOpportunities,bestOpportunity:responseResult(best,1),bestTradeNow:bestTradeResponse};
}
