//! Secrets live only in the OS credential store: macOS Keychain, Windows
//! Credential Manager (Linux: Secret Service). Never in source, never in the
//! SQLite file, never in the webview (no localStorage, and no command returns
//! a secret value to the frontend -- only whether one is configured).
//!
//! Two kinds of secret:
//! - the local execution-service API key: generated by the app, used as the
//!   X-API-Key between this controller and the service it launches;
//! - exchange TESTNET credentials (Binance USDT-M Futures Testnet), which the
//!   operator can store for the future testnet mode. Mainnet credentials have
//!   no slot here at all.

use rand::RngCore;

pub const SERVICE: &str = "market-edge-desktop";
pub const EXEC_API_KEY: &str = "execution-service-api-key";

/// The only names the frontend may write. Anything else is refused, so the
/// UI cannot be used to plant arbitrary entries (or a mainnet key slot).
pub const OPERATOR_SECRETS: &[&str] = &["binance-testnet-api-key", "binance-testnet-api-secret"];

#[derive(Debug)]
pub enum SecretError {
    NotAllowed(String),
    Invalid(String),
    Store(String),
}

impl std::fmt::Display for SecretError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SecretError::NotAllowed(n) => write!(f, "secret '{n}' is not an operator-settable secret"),
            SecretError::Invalid(m) => write!(f, "invalid secret: {m}"),
            SecretError::Store(m) => write!(f, "OS credential store error: {m}"),
        }
    }
}

/// Storage backend. Production uses the OS keyring; unit tests use an
/// in-memory map so they never touch the developer's real keychain.
pub trait SecretBackend: Send + Sync {
    fn get(&self, name: &str) -> Result<Option<String>, SecretError>;
    fn set(&self, name: &str, value: &str) -> Result<(), SecretError>;
    fn delete(&self, name: &str) -> Result<(), SecretError>;
    fn describe(&self) -> &'static str;
}

pub struct OsKeyring {
    service: String,
}

impl OsKeyring {
    pub fn new(service: &str) -> Self {
        OsKeyring { service: service.to_string() }
    }
    fn entry(&self, name: &str) -> Result<keyring::Entry, SecretError> {
        keyring::Entry::new(&self.service, name).map_err(|e| SecretError::Store(e.to_string()))
    }
}

impl SecretBackend for OsKeyring {
    fn get(&self, name: &str) -> Result<Option<String>, SecretError> {
        match self.entry(name)?.get_password() {
            Ok(v) => Ok(Some(v)),
            Err(keyring::Error::NoEntry) => Ok(None),
            Err(e) => Err(SecretError::Store(e.to_string())),
        }
    }
    fn set(&self, name: &str, value: &str) -> Result<(), SecretError> {
        self.entry(name)?.set_password(value).map_err(|e| SecretError::Store(e.to_string()))
    }
    fn delete(&self, name: &str) -> Result<(), SecretError> {
        match self.entry(name)?.delete_credential() {
            Ok(()) | Err(keyring::Error::NoEntry) => Ok(()),
            Err(e) => Err(SecretError::Store(e.to_string())),
        }
    }
    fn describe(&self) -> &'static str {
        if cfg!(target_os = "macos") {
            "macOS Keychain"
        } else if cfg!(target_os = "windows") {
            "Windows Credential Manager"
        } else {
            "Secret Service (Linux)"
        }
    }
}

#[derive(Default)]
pub struct MemoryBackend {
    map: std::sync::Mutex<std::collections::HashMap<String, String>>,
}

impl SecretBackend for MemoryBackend {
    fn get(&self, name: &str) -> Result<Option<String>, SecretError> {
        Ok(self.map.lock().unwrap().get(name).cloned())
    }
    fn set(&self, name: &str, value: &str) -> Result<(), SecretError> {
        self.map.lock().unwrap().insert(name.to_string(), value.to_string());
        Ok(())
    }
    fn delete(&self, name: &str) -> Result<(), SecretError> {
        self.map.lock().unwrap().remove(name);
        Ok(())
    }
    fn describe(&self) -> &'static str {
        "in-memory (not persisted)"
    }
}

pub fn generate_api_key() -> String {
    let mut bytes = [0u8; 32];
    rand::thread_rng().fill_bytes(&mut bytes);
    hex::encode(bytes)
}

/// Where the execution-service API key came from this session.
#[derive(Debug, Clone, serde::Serialize)]
pub struct ApiKeySource {
    pub persisted: bool,
    pub store: String,
    pub warning: Option<String>,
}

/// Reads the service API key from the credential store, creating it on first
/// run. If the OS store is unavailable (e.g. a headless Linux box with no
/// Secret Service), falls back to a key that exists only in this process's
/// memory -- never to a file.
pub fn service_api_key(backend: &dyn SecretBackend) -> (String, ApiKeySource) {
    match backend.get(EXEC_API_KEY) {
        Ok(Some(key)) if key.len() >= 32 => {
            return (key, ApiKeySource { persisted: true, store: backend.describe().into(), warning: None });
        }
        Ok(_) => {
            let key = generate_api_key();
            match backend.set(EXEC_API_KEY, &key) {
                Ok(()) => return (key, ApiKeySource { persisted: true, store: backend.describe().into(), warning: None }),
                Err(e) => {
                    return (key, ApiKeySource { persisted: false, store: "memory only".into(), warning: Some(e.to_string()) });
                }
            }
        }
        Err(e) => {
            let key = generate_api_key();
            (key, ApiKeySource { persisted: false, store: "memory only".into(), warning: Some(e.to_string()) })
        }
    }
}

pub fn set_operator_secret(backend: &dyn SecretBackend, name: &str, value: &str) -> Result<(), SecretError> {
    if !OPERATOR_SECRETS.contains(&name) {
        return Err(SecretError::NotAllowed(name.to_string()));
    }
    let value = value.trim();
    if value.is_empty() || value.len() > 512 || value.chars().any(|c| c.is_control()) {
        return Err(SecretError::Invalid("must be 1-512 printable characters".into()));
    }
    backend.set(name, value)
}

pub fn delete_operator_secret(backend: &dyn SecretBackend, name: &str) -> Result<(), SecretError> {
    if !OPERATOR_SECRETS.contains(&name) {
        return Err(SecretError::NotAllowed(name.to_string()));
    }
    backend.delete(name)
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct SecretStatus {
    pub name: String,
    pub configured: bool,
    pub error: Option<String>,
}

/// Presence only -- never the value.
pub fn operator_secret_status(backend: &dyn SecretBackend) -> Vec<SecretStatus> {
    OPERATOR_SECRETS
        .iter()
        .map(|name| match backend.get(name) {
            Ok(v) => SecretStatus { name: name.to_string(), configured: v.is_some(), error: None },
            Err(e) => SecretStatus { name: name.to_string(), configured: false, error: Some(e.to_string()) },
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn api_key_is_created_once_and_reused() {
        let backend = MemoryBackend::default();
        let (first, source) = service_api_key(&backend);
        assert!(source.persisted);
        assert_eq!(first.len(), 64);
        let (second, _) = service_api_key(&backend);
        assert_eq!(first, second);
    }

    #[test]
    fn only_allowlisted_operator_secrets_can_be_written() {
        let backend = MemoryBackend::default();
        assert!(matches!(set_operator_secret(&backend, "binance-mainnet-api-key", "x"), Err(SecretError::NotAllowed(_))));
        assert!(matches!(set_operator_secret(&backend, EXEC_API_KEY, "x"), Err(SecretError::NotAllowed(_))));
        assert!(matches!(set_operator_secret(&backend, "binance-testnet-api-key", "  "), Err(SecretError::Invalid(_))));
        set_operator_secret(&backend, "binance-testnet-api-key", "abc123").unwrap();
        let status = operator_secret_status(&backend);
        assert!(status.iter().any(|s| s.name == "binance-testnet-api-key" && s.configured));
        assert!(status.iter().any(|s| s.name == "binance-testnet-api-secret" && !s.configured));
        // status never carries the value
        assert!(!serde_json::to_string(&status).unwrap().contains("abc123"));
        delete_operator_secret(&backend, "binance-testnet-api-key").unwrap();
        assert!(operator_secret_status(&backend).iter().all(|s| !s.configured));
    }

    struct Broken;
    impl SecretBackend for Broken {
        fn get(&self, _: &str) -> Result<Option<String>, SecretError> {
            Err(SecretError::Store("no keyring".into()))
        }
        fn set(&self, _: &str, _: &str) -> Result<(), SecretError> {
            Err(SecretError::Store("no keyring".into()))
        }
        fn delete(&self, _: &str) -> Result<(), SecretError> {
            Err(SecretError::Store("no keyring".into()))
        }
        fn describe(&self) -> &'static str {
            "broken"
        }
    }

    #[test]
    fn unavailable_keyring_falls_back_to_memory_never_to_disk() {
        let (key, source) = service_api_key(&Broken);
        assert_eq!(key.len(), 64);
        assert!(!source.persisted);
        assert!(source.warning.is_some());
    }

    /// Real OS credential store round trip. Opt-in (it writes to the real
    /// keychain): CI runs it on macOS and Windows with MARKET_EDGE_KEYRING_TEST=1.
    #[test]
    fn os_keyring_round_trip() {
        if std::env::var("MARKET_EDGE_KEYRING_TEST").ok().as_deref() != Some("1") {
            eprintln!("skipped: set MARKET_EDGE_KEYRING_TEST=1 to exercise the real OS keyring");
            return;
        }
        let backend = OsKeyring::new("market-edge-desktop-ci-test");
        let name = "binance-testnet-api-key";
        backend.delete(name).unwrap();
        assert_eq!(backend.get(name).unwrap(), None);
        set_operator_secret(&backend, name, "ci-test-value").unwrap();
        assert_eq!(backend.get(name).unwrap().as_deref(), Some("ci-test-value"));
        let (key, source) = service_api_key(&backend);
        assert!(source.persisted, "{:?}", source.warning);
        assert_eq!(service_api_key(&backend).0, key);
        backend.delete(name).unwrap();
        backend.delete(EXEC_API_KEY).unwrap();
        assert_eq!(backend.get(name).unwrap(), None);
        println!("KEYRING_ROUND_TRIP_OK store={}", backend.describe());
    }
}
