"""Test 1: JS/Python contract round-trip. Loads fixtures produced by the
actual JS domain-objects.js factory functions (tests/fixtures/js_contracts.json,
regenerated by running the Node snippet documented at the top of that file)
and asserts every field name/value the JS side produced is reproduced
byte-for-byte by the Python .create()/.to_dict() round-trip. No silent field
renaming: this test fails immediately if either side drifts.
"""
import json
from pathlib import Path

from market_edge_exec.domain.contracts import (
    AlphaSignal, ExecutionFill, ExecutionIntent, PortfolioDecision, PositionSnapshot, RiskDecision,
)

FIXTURES = json.loads((Path(__file__).parent / "fixtures" / "js_contracts.json").read_text())

CONTRACTS = {
    "AlphaSignal": AlphaSignal, "RiskDecision": RiskDecision, "PortfolioDecision": PortfolioDecision,
    "ExecutionIntent": ExecutionIntent, "ExecutionFill": ExecutionFill, "PositionSnapshot": PositionSnapshot,
}


def test_every_js_fixture_field_round_trips_through_python():
    for name, cls in CONTRACTS.items():
        js_payload = FIXTURES[name]
        python_obj = cls.create(js_payload)
        python_payload = python_obj.to_dict()
        for field, value in js_payload.items():
            assert python_payload[field] == value, f"{name}.{field}: JS={value!r} Python={python_payload[field]!r}"


def test_python_contracts_carry_schema_and_version_js_side_can_check():
    for name, cls in CONTRACTS.items():
        obj = cls.create(FIXTURES[name])
        assert obj.to_dict()["schema"] == name
        assert obj.to_dict()["version"]


def test_missing_required_field_is_rejected_on_both_sides_the_same_way():
    broken = dict(FIXTURES["ExecutionIntent"])
    del broken["quantity"]
    try:
        ExecutionIntent.create(broken)
        assert False, "expected ContractError"
    except Exception as error:
        assert "EXECUTION_INTENT_INVALID" in str(error)
